apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y1c665q7k-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y1c665q7k-go 
  name: y1c665q7k-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: y1c665q7k-go 
